# Generated by Django 3.0.4 on 2020-03-26 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=10)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_loaned', models.BooleanField(default=False)),
            ],
        ),
    ]
