# Generated by Django 3.0.4 on 2020-03-26 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0002_auto_20200326_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmaterial',
            name='id',
        ),
    ]
