# Generated by Django 3.0.4 on 2020-03-26 10:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0004_auto_20200326_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='uploaded_by',
            field=models.IntegerField(default=django.contrib.auth.models.User),
        ),
    ]
