# Generated by Django 3.0.4 on 2020-03-26 10:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0005_auto_20200326_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='uploaded_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
