# Generated by Django 3.0.4 on 2020-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0006_auto_20200326_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmaterial',
            name='uploaded_by',
        ),
    ]
