# Generated by Django 3.0.4 on 2020-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0007_remove_addmaterial_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmaterial',
            name='is_loaned',
        ),
        migrations.AddField(
            model_name='addmaterial',
            name='quantity_available',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmaterial',
            name='quantity_loaned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
