# Generated by Django 3.0.4 on 2020-03-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0008_auto_20200327_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='quantity_loaned',
            field=models.IntegerField(default=0),
        ),
    ]
