# Generated by Django 3.0.4 on 2020-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0010_publishmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishmaterial',
            name='is_loaned',
            field=models.BooleanField(default=False),
        ),
    ]
