# Generated by Django 3.0.4 on 2020-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0011_publishmaterial_is_loaned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmaterial',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='addmaterial',
            name='quantity_loaned',
        ),
        migrations.AlterField(
            model_name='addmaterial',
            name='year',
            field=models.IntegerField(),
        ),
    ]
