# Generated by Django 3.0.4 on 2020-03-29 09:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addmaterial', '0009_auto_20200327_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_datetime', models.DateTimeField(default=datetime.datetime(2020, 3, 29, 11, 30, 54, 665061))),
                ('is_returned', models.BooleanField(default=False)),
                ('is_returned_datetime', models.DateTimeField(default=None)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmaterial.Addmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
