# Generated by Django 3.0.4 on 2020-03-29 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200329_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_returned_datetime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 11, 38, 12, 734720)),
        ),
    ]
