# Generated by Django 3.0.4 on 2020-03-29 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20200329_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_returned_datetime',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 11, 38, 37, 32386)),
        ),
    ]
