# Generated by Django 3.0.4 on 2020-03-29 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200329_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 12, 27, 52, 196734)),
        ),
    ]
