# Generated by Django 3.0.4 on 2020-03-29 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_auto_20200329_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 22, 45, 40, 209985)),
        ),
    ]
