# Generated by Django 3.0.4 on 2020-03-31 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_auto_20200329_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 13, 0, 48, 477908)),
        ),
    ]
